### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by glaav** [kennytv/kennytvs-epic-force-close-loading-screen-mod-for-fabric#13]
Not sure if this is the mod causing the issue, but on 2.0.0 it didn't happen, on 2.1.0 it does.
[error.txt](https://github.com/kennytv/kennytvs-epic-force-close-loading-screen-mod-for-fabric/files/11325570/error.txt)

**Comment by kennytv** [comment]
What is your Minecraft version? Please try removing other mods/find which might be causing troubles due to incompatibility

**Comment by glaav** [comment]
so this is the complete log + mod list, testing all the mods now
https://mclo.gs/coUmdT5

**Comment by kennytv** [comment]
Most likely fastload

**Comment by glaav** [comment]
confirmed.
is the fix planned?

**Comment by kennytv** [comment]
I don't know how to "disable" that particular mixin without just refusing to load with it, I'm no modding expert. That particular feature of disabling the "Loading World" screen is also in FastLoad, although it doesn't properly keep vanilla's cleaning logic

**Comment by glaav** [comment]
well i guess ill stay on 2.0 then ¯\_(ツ)_/¯
