### ISSUE TITLE
Error with 2.1.0

### ISSUE THREAD

**Issue by NoltoxGit** [kennytv/kennytvs-epic-force-close-loading-screen-mod-for-fabric#14]
Hello,
I have an error when I start fabric with the latest update

Fabric error [here](https://pastebin.com/raw/5dBsC3dP).
Latest.log [here](https://mclo.gs/0bRwRg7).

**Comment by kennytv** [comment]
Fastload is incompatile with this mod

**Comment by NoltoxGit** [comment]
> Fastload is incompatile with this mod

Okay, I removed this mod and everything works fine, tysm !
