### ISSUE TITLE
Unresolved dependency fabric

### ISSUE THREAD

**Issue by QazCetelic** [kennytv/kennytvs-epic-force-close-loading-screen-mod-for-fabric#4]
The **Fabric** mod loader displays a dependency error where it shows that the mod requires fabric which supposedly isn't loaded, but it clearly is.

![Fabric Loader Error](https://user-images.githubusercontent.com/51381523/158682332-5ee1ce84-e624-4b26-b85e-75f2e94da62b.png)

**Comment by mdcfe** [comment]
You need to install [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api). This is a separate mod which is required for almost all Fabric Loader mods.
